grafana:
  enabled: true
  adminPassword: "ChangeMe-Interview"
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 12h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
