name: 🚀 CD Dev

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

concurrency:
  group: cd-dev-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: 🐳 Build & Push (DEV → ECR)
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@master
    with:
      environment: dev
      project: org-app
      aws-region: us-east-1
      registry: 597088058179.dkr.ecr.us-east-1.amazonaws.com
      dockerfile-path: Dockerfile
      context: .
      version-prefix: "0.0"
    secrets: inherit

  deploy:
    name: ☸️ Deploy (DEV → EKS)
    needs: build
    uses: YuriMarco94/pipeline-templates/.github/workflows/deploy-template-eks.yml@master
    with:
      aws-region: us-east-1
      eks-cluster-name: yurim-aws-platform-dev-us-east-1-eks
      namespace: dev
      manifest-path: k8s/apps/namespaces/dev/
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
