name: CD Dev

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@master
    secrets: inherit
    with:
      environment: dev
      aws-region: us-east-1
      ecr-repository: org-app
      dockerfile-path: Dockerfile
      context: .
      tag-strategy: sha

  deploy:
    needs: [build]
    uses: YuriMarco94/pipeline-templates/.github/workflows/deploy-template-eks.yml@master
    secrets: inherit
    with:
      aws-region: us-east-1
      eks-cluster-name: yurim-aws-platform-dev-us-east-1-eks
      manifest-path: k8s/apps/namespaces/dev/
      namespace: dev
      deployment-name: echo
      container-name: echo
      image-uri: ${{ needs.build.outputs.image-uri }}
      rollout-timeout: 180s
