name: CD Dev

on:
  push:
    branches: [ "homol" ]
  workflow_dispatch:

jobs:
  build:
<<<<<<< HEAD
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@master
    secrets: inherit
=======
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@main
>>>>>>> 830827c (Ajustes DEV)
    with:
      environment: hom
      project: org-app
      aws-region: us-east-1
      registry: 597088058179.dkr.ecr.us-east-1.amazonaws.com
      dockerfile-path: Dockerfile
      context: .
      version-prefix: "0.0"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: build
    uses: YuriMarco94/pipeline-templates/.github/workflows/deploy-template-eks.yml@main
    with:
      aws-region: us-east-1
      eks-cluster-name: yurim-aws-platform-dev-us-east-1-eks
      namespace: hom
      manifest-path: k8s/apps/namespaces/hom/
      image: ${{ needs.build.outputs.image }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
