name: CD Prod

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@master
    secrets: inherit
    with:
      environment: prod
      project: org-app
      aws-region: us-east-1
      registry: 597088058179.dkr.ecr.us-east-1.amazonaws.com
      dockerfile-path: Dockerfile
      context: .
      version-prefix: "1.0"

  deploy:
    needs: build
    uses: YuriMarco94/pipeline-templates/.github/workflows/deploy-template-eks.yml@master
    secrets: inherit
    with:
      aws-region: us-east-1
      eks-cluster-name: yurim-aws-platform-dev-us-east-1-eks
      namespace: prod
      manifest-path: k8s/apps/namespaces/prod/
      image: ${{ needs.build.outputs.image }}
