name: Desenvolvimento-AWS

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    uses: YuriMarco94/pipeline-templates/.github/workflows/build-template-aws.yml@master
    secrets: inherit
    with:
      build-id: ${{ github.run_id }}
      environment: dev
      namespace: demo
      project: Desenvolvimento-AWS
      registry: ${{ vars.ECR_REGISTRY }}
      aws-region: ${{ vars.AWS_REGION }}
      dockerfile-path: Dockerfile
      context: .
      version-prefix: "0.0"

  deploy:
    needs: build
    uses: YuriMarco94/pipeline-templates/.github/workflows/deploy-template-eks.yml@master
    secrets: inherit
    with:
      environment: dev
      namespace: demo
      aws-region: ${{ vars.AWS_REGION }}
      eks-cluster-name: ${{ vars.EKS_CLUSTER_NAME }}
      manifest-path: kubernetes/manifests
